"""Project workspace layout (Phase O).

Phase O consolidates the per-project workspace at
`~/Research/{project-slug}/` (PI-chosen slug) — the canonical home
for everything related to one research project:

    ~/Research/iot-edge-llm/
    ├── .rka/
    │   ├── project_id          # one line: prj_…
    │   ├── workspace.json      # phase status, last-update ts, hashes
    │   ├── tools.json          # Phase D manifest (baseline)
    │   ├── extension_*.json    # per-mission extensions
    │   └── .env                # mode 0600, gitignored
    ├── data/                   # research datasets
    ├── code/                   # implementation
    ├── notebooks/              # exploratory analysis
    ├── manuscripts/{venue}/    # Writer skill workspace
    ├── results/                # experiment outputs
    ├── README.md               # auto-generated; describes the project's plan
    └── .gitignore              # auto: .rka/.env, results/

The workspace is NEVER inside the rka repo — it lives in the PI's home
directory. The rka repo holds only the orchestrator code that knows
how to create it.

Separate from `manifest.workspace_dir()` which manages the legacy
Phase D MVP convention at `~/rka-projects/{project_id}/`. Phase O will
eventually migrate D MVP projects to the new layout; until then both
co-exist.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Constants + env-var overrides
# ---------------------------------------------------------------------------

# Default workspace root. Override via `RKA_WORKSPACE_ROOT` env var
# (useful for tests + container mounts that don't follow the convention).
DEFAULT_WORKSPACE_ROOT_ENV = "RKA_WORKSPACE_ROOT"
DEFAULT_WORKSPACE_ROOT_NAME = "Research"

# .rka subdir holds orchestrator-owned project metadata.
RKA_SUBDIR = ".rka"
PROJECT_ID_FILE = "project_id"
WORKSPACE_JSON = "workspace.json"

# Default project sub-directories created at workspace_setup time.
# These names match conventions in the Writer skill (manuscripts/) and
# what the design doc canonicalizes. PI may add their own dirs but the
# orchestrator only auto-creates these.
DEFAULT_SUBDIRS = ("data", "code", "notebooks", "manuscripts", "results")

# Slug validation — kebab-case, 3-40 chars, must start with a letter.
# Empirical filesystem-friendly subset; allows hyphens but not
# underscores, dots, or spaces.
SLUG_PATTERN = re.compile(r"^[a-z][a-z0-9-]{2,39}$")

# Auto-generated .gitignore for the workspace (lives at workspace root
# in case PI initializes git here). Distinct from the rka repo's own
# .gitignore (which doesn't need any new entries — the workspace lives
# outside the repo tree entirely).
WORKSPACE_GITIGNORE_CONTENT = """\
# Auto-generated by orchestrator (Phase O workspace_setup).
# Edit if you initialize this workspace as its own git repo.

# Credentials — NEVER commit
.rka/.env
.env

# Large / transient outputs
results/
*.log
*.tmp

# Python / OS scratch
__pycache__/
.ipynb_checkpoints/
.DS_Store
"""


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class WorkspaceError(Exception):
    """Base for workspace.py errors so callers can catch the family."""


class InvalidSlugError(WorkspaceError):
    """The slug doesn't match the kebab-case validation regex."""


class WorkspaceAlreadyExistsError(WorkspaceError):
    """The target workspace path exists. Phase O refuses to overwrite —
    PI must pick a different slug or remove the existing dir."""


class WorkspaceNotFoundError(WorkspaceError):
    """The workspace dir is missing — caller expected it to exist."""


class WorkspaceCorruptError(WorkspaceError):
    """The workspace dir exists but its metadata is malformed
    (missing or unreadable `.rka/project_id` or `workspace.json`)."""


# ---------------------------------------------------------------------------
# ProjectSlug dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ProjectSlug:
    """Binding between an RKA project id and its workspace identity.

    The slug is the PI-facing name (used as the path component); the
    rka_project_id is the persistent canonical reference. Both are
    written to disk at `.rka/project_id`; this dataclass is the
    in-process representation.
    """

    slug: str
    rka_project_id: str

    def __post_init__(self):
        if not SLUG_PATTERN.match(self.slug):
            raise InvalidSlugError(
                f"slug {self.slug!r} must match /{SLUG_PATTERN.pattern}/: "
                f"lowercase letters/digits/hyphens, 3-40 chars, starts with a letter."
            )
        if not self.rka_project_id.startswith("prj_"):
            raise InvalidSlugError(
                f"rka_project_id {self.rka_project_id!r} must start with 'prj_'"
            )

    @property
    def workspace_path(self) -> Path:
        """The absolute path to this slug's workspace dir."""
        return project_workspace(self.slug)

    @property
    def rka_dir(self) -> Path:
        """The `.rka/` subdir holding orchestrator-owned metadata."""
        return self.workspace_path / RKA_SUBDIR


# ---------------------------------------------------------------------------
# Slug derivation
# ---------------------------------------------------------------------------


def derive_slug_from_name(name: str, *, max_len: int = 40) -> str:
    """Auto-generate a slug from an RKA project name.

    Examples:
      "IoT Edge LLM Hosting (MLSys 2026)" → "iot-edge-llm-hosting-mlsys-2026"
      "Quick & Dirty Prototype!"           → "quick-dirty-prototype"
      "x"                                   → "rka-x" (forces ≥3 chars + letter start)

    Algorithm:
      1. Lowercase
      2. Replace any non-alphanumeric with hyphen
      3. Collapse runs of hyphens; strip leading/trailing hyphens
      4. Truncate to max_len chars
      5. If result is empty or doesn't start with a letter or is <3 chars,
         prefix with "rka-" (e.g., "rka-2026", "rka-x")
      6. If still invalid, raise InvalidSlugError (shouldn't happen with
         reasonable inputs)
    """
    if not name or not isinstance(name, str):
        raise InvalidSlugError("project name must be a non-empty string")

    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    s = s[:max_len].rstrip("-")  # don't end on a hyphen after truncation

    # Ensure starts with letter + ≥3 chars.
    if not s or not s[0].isalpha() or len(s) < 3:
        s = f"rka-{s}".rstrip("-")
        s = s[:max_len].rstrip("-")

    if not SLUG_PATTERN.match(s):
        raise InvalidSlugError(
            f"could not derive a valid slug from {name!r}; got {s!r}"
        )
    return s


# ---------------------------------------------------------------------------
# Workspace path resolution
# ---------------------------------------------------------------------------


def workspace_root() -> Path:
    """The default root for all project workspaces.

    Returns `$RKA_WORKSPACE_ROOT` if set (typically tests + container
    mounts); else `$HOME/Research`.
    """
    env = os.environ.get(DEFAULT_WORKSPACE_ROOT_ENV)
    if env:
        return Path(env)
    return Path.home() / DEFAULT_WORKSPACE_ROOT_NAME


def project_workspace(slug: str) -> Path:
    """Absolute path for a project's workspace dir."""
    return workspace_root() / slug


def rka_dir(slug: str) -> Path:
    """Absolute path for the `.rka/` subdir."""
    return project_workspace(slug) / RKA_SUBDIR


def project_id_file(slug: str) -> Path:
    """Where `.rka/project_id` lives."""
    return rka_dir(slug) / PROJECT_ID_FILE


def workspace_json_path(slug: str) -> Path:
    """Where `.rka/workspace.json` lives."""
    return rka_dir(slug) / WORKSPACE_JSON


# ---------------------------------------------------------------------------
# Workspace creation + metadata
# ---------------------------------------------------------------------------


def _now_iso() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def create_workspace(
    slug: str,
    rka_project_id: str,
    *,
    refuse_if_exists: bool = True,
    write_readme: bool = True,
    write_gitignore: bool = True,
) -> ProjectSlug:
    """Materialize the project workspace on disk.

    Algorithm:
      1. Validate slug (via ProjectSlug constructor).
      2. If target dir exists AND refuse_if_exists → raise
         WorkspaceAlreadyExistsError. (Phase O default behavior; tests
         can override with refuse_if_exists=False to allow idempotency.)
      3. mkdir the workspace + .rka + default subdirs with mode 0700.
      4. Write `.rka/project_id` (one-line: prj_… ID).
      5. Write `.rka/workspace.json` (phase status, schema version).
      6. Optional: write a README.md stub.
      7. Optional: write the workspace's own .gitignore.

    Returns the ProjectSlug binding for use by callers.
    """
    binding = ProjectSlug(slug=slug, rka_project_id=rka_project_id)
    target = binding.workspace_path

    if target.exists() and refuse_if_exists:
        raise WorkspaceAlreadyExistsError(
            f"workspace already exists at {target} — pick a different slug "
            f"or remove the directory. (Phase O onboarding refuses to "
            f"overwrite existing workspaces.)"
        )

    target.mkdir(parents=True, exist_ok=True)
    try:
        target.chmod(0o700)
    except OSError:
        # Some filesystems don't support POSIX perms; secrets-file mode
        # 0600 still applies inside .rka/.
        pass

    rka_subdir = binding.rka_dir
    rka_subdir.mkdir(parents=True, exist_ok=True)
    try:
        rka_subdir.chmod(0o700)
    except OSError:
        pass

    for sub in DEFAULT_SUBDIRS:
        (target / sub).mkdir(parents=True, exist_ok=True)

    # .rka/project_id — one line, no newline, since callers may shell-read.
    project_id_file(slug).write_text(rka_project_id, encoding="utf-8")

    # .rka/workspace.json — phase tracking.
    workspace_meta = {
        "schema_version": "v1",
        "rka_project_id": rka_project_id,
        "slug": slug,
        "created_at": _now_iso(),
        "phase": "init",  # init | o1 | o2 | o3 | o4 | o5 | handoff | active | archived
        "phase_history": [],
        "last_updated": _now_iso(),
    }
    workspace_json_path(slug).write_text(
        json.dumps(workspace_meta, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    if write_readme:
        readme = target / "README.md"
        if not readme.exists():
            readme.write_text(
                f"# {slug}\n\n"
                f"RKA project: `{rka_project_id}`\n\n"
                f"Created by orchestrator onboarding at {_now_iso()}.\n\n"
                f"This workspace will be populated by subsequent onboarding "
                f"sub-phases (idea capture, deep research, plan synthesis, "
                f"tool setup). See `~/Research/{slug}/.rka/workspace.json` "
                f"for phase status.\n",
                encoding="utf-8",
            )

    if write_gitignore:
        gi = target / ".gitignore"
        if not gi.exists():
            gi.write_text(WORKSPACE_GITIGNORE_CONTENT, encoding="utf-8")

    return binding


def load_workspace_meta(slug: str) -> dict:
    """Read `.rka/workspace.json` for a project.

    Raises WorkspaceNotFoundError if the dir doesn't exist;
    WorkspaceCorruptError if the metadata is missing or malformed.
    """
    target = project_workspace(slug)
    if not target.is_dir():
        raise WorkspaceNotFoundError(f"workspace not found at {target}")
    meta_path = workspace_json_path(slug)
    if not meta_path.is_file():
        raise WorkspaceCorruptError(
            f"workspace.json missing at {meta_path} — was the workspace "
            f"created by Phase O onboarding?"
        )
    try:
        return json.loads(meta_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise WorkspaceCorruptError(
            f"workspace.json at {meta_path} is malformed JSON: {e}"
        ) from e


def save_workspace_meta(slug: str, meta: dict) -> None:
    """Overwrite `.rka/workspace.json`. Bumps `last_updated`.

    Phase tracking pattern: callers fetch via load_workspace_meta,
    mutate the `phase` field + append to `phase_history`, then call
    save_workspace_meta. Atomic-write isn't critical here (single PI,
    no concurrent writers expected) but the write goes through a
    temp-file rename for robustness against partial writes.
    """
    meta = dict(meta)
    meta["last_updated"] = _now_iso()
    target_path = workspace_json_path(slug)
    if not target_path.parent.exists():
        raise WorkspaceNotFoundError(
            f"cannot save workspace.json to {target_path} — parent dir missing"
        )
    tmp = target_path.with_suffix(".json.tmp")
    tmp.write_text(
        json.dumps(meta, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    tmp.replace(target_path)


def advance_phase(slug: str, new_phase: str, *, note: Optional[str] = None) -> dict:
    """Convenience: read meta, append the current phase to
    phase_history, set phase to new_phase, save.

    Idempotent on re-advance (if new_phase == current phase, just
    refreshes last_updated). Returns the updated meta dict.
    """
    meta = load_workspace_meta(slug)
    current = meta.get("phase", "init")
    if current != new_phase:
        history_entry = {
            "phase": current,
            "exited_at": _now_iso(),
        }
        if note:
            history_entry["note"] = note
        meta.setdefault("phase_history", []).append(history_entry)
        meta["phase"] = new_phase
    save_workspace_meta(slug, meta)
    return meta


def find_workspace_for_project_id(rka_project_id: str) -> Optional[ProjectSlug]:
    """Reverse-lookup: given an RKA project_id, find its workspace
    (if one exists). Walks workspace_root() looking for
    `.rka/project_id` files matching.

    Returns None if no workspace is bound to this project_id.
    Useful when the orchestrator daemon resumes and needs to locate
    workspace metadata from a project_id alone.
    """
    root = workspace_root()
    if not root.is_dir():
        return None
    for child in root.iterdir():
        if not child.is_dir():
            continue
        pid_file = child / RKA_SUBDIR / PROJECT_ID_FILE
        if not pid_file.is_file():
            continue
        try:
            stored = pid_file.read_text(encoding="utf-8").strip()
        except OSError:
            continue
        if stored == rka_project_id:
            try:
                return ProjectSlug(slug=child.name, rka_project_id=stored)
            except InvalidSlugError:
                continue  # dir exists but its name isn't slug-valid; skip
    return None
