#!/usr/bin/env python3
"""venue_md_generator.py — render <id>.md from <id>.yaml + optional tail.

Reads the venue spec (via venue_loader.load_venue) and emits a narrative
markdown file with section ordering that matches the original Phase 2
seven-section convention (sections / page limit / tone / forbidden /
citation / required / sample corpus + Template notes + References).

If a sibling `<id>.notes.md` file exists, its contents are appended below
an auto-generated separator. The auto-generated region is delimited by:

    <!-- BEGIN auto-generated by venue_md_generator.py -->
    ...
    <!-- END auto-generated by venue_md_generator.py -->

so subsequent regenerations only replace that block. Anything above or
below the markers is preserved verbatim.

CLI:
    python venue_md_generator.py NeurIPS           # write rka/.../venue/NeurIPS.md
    python venue_md_generator.py --all             # regenerate every venue's .md
    python venue_md_generator.py NeurIPS --stdout  # print without writing
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

# Phase W1: support both invocation patterns —
#   (a) `python venue_md_generator.py ...` from anywhere (venue_loader.py
#       lives next door on disk).
#   (b) importlib loading from tests (the importing parent puts neither
#       venue_loader nor this script's dir on sys.path).
# Add this script's directory to sys.path so the sibling import lands.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from venue_loader import (  # noqa: E402  (sys.path mutation above)
    PROPOSAL_DIR,
    PROPOSAL_SOL_DIR,
    SKILL_ROOT,
    VENUE_DIR,
    Venue,
    load_all_venues,
    load_venue,
)

BEGIN_MARKER = "<!-- BEGIN auto-generated by venue_md_generator.py -->"
END_MARKER = "<!-- END auto-generated by venue_md_generator.py -->"


def _md_path(venue_id: str) -> Path:
    for root in (VENUE_DIR, PROPOSAL_DIR, PROPOSAL_SOL_DIR):
        if (root / f"{venue_id}.yaml").is_file():
            return root / f"{venue_id}.md"
    raise FileNotFoundError(f"no .yaml found for {venue_id}")


def _notes_path(venue_id: str) -> Optional[Path]:
    for root in (VENUE_DIR, PROPOSAL_DIR, PROPOSAL_SOL_DIR):
        candidate = root / f"{venue_id}.notes.md"
        if candidate.is_file():
            return candidate
    return None


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------


def _header(v: Venue) -> list[str]:
    lines = [
        f"# {v.name}",
        "",
        f"> Auto-generated from `{v.id}.yaml` by `venue_md_generator.py`. "
        f"Do NOT edit the auto-generated region by hand - re-run the generator. "
        f"Add freeform notes to `{v.id}.notes.md`; they will be appended.",
        "",
        f"- **ID**: `{v.id}`",
        f"- **Kind**: {v.kind}",
        f"- **Domain**: {v.domain}",
        f"- **Pinned year**: {v.pin_year or '(unpinned)'}",
        f"- **Status**: {v.status}",
        "",
    ]
    return lines


def _section_sections_and_order(v: Venue) -> list[str]:
    s = v.structure
    out = ["## 1. Section names and order", ""]
    if s.required_sections:
        out.append("**Required sections:**")
        out.append("")
        for sec in s.required_sections:
            out.append(f"  - {sec}")
        out.append("")
    if s.optional_sections:
        out.append("**Optional sections:**")
        out.append("")
        for sec in s.optional_sections:
            out.append(f"  - {sec}")
        out.append("")
    if s.section_order:
        out.append("**Canonical order when present:**")
        out.append("")
        for i, sec in enumerate(s.section_order, 1):
            out.append(f"{i}. {sec}")
        out.append("")
    if s.appendix_sections:
        out.append("**Typical appendix contents:**")
        out.append("")
        for sec in s.appendix_sections:
            out.append(f"  - {sec}")
        out.append("")
    return out


def _section_page_limit(v: Venue) -> list[str]:
    s = v.submission
    out = ["## 2. Page-limit class", ""]
    if s.page_limit_main is None:
        out.append("- Main matter: **no hard limit** (e.g., journal).")
    else:
        out.append(f"- Main matter: **{s.page_limit_main} pages**.")
    if s.page_limit_camera_ready and s.page_limit_camera_ready != s.page_limit_main:
        out.append(f"- Camera-ready: **{s.page_limit_camera_ready} pages**.")
    out.append(
        f"- References: **{'counted' if s.references_counted else 'uncounted'}**."
    )
    out.append(
        f"- Appendix: **{'counted' if s.appendix_counted else 'uncounted'}**"
        + (
            f", limit {s.appendix_limit} pages."
            if s.appendix_limit is not None
            else "."
        )
    )
    if s.has_required_checklist:
        out.append("- Has a **required checklist** (e.g., reproducibility / paper checklist).")
    out.append(f"- Anonymization: **{s.anonymization.replace('_', ' ')}**.")
    out.append("")
    return out


def _section_tone(v: Venue) -> list[str]:
    t = v.tone
    out = ["## 3. Tone characteristics", ""]
    bullets = [
        f"- Voice: **{t.voice.replace('-', ' ')}**.",
        f"- Hedging: **{t.hedging}**.",
        f"- Marketing language: **{t.marketing_language}**.",
        f"- Math density: **{t.math_density}**.",
        f"- Reproducibility floor: **{t.reproducibility_floor}**.",
    ]
    if t.numerical_claims_dominate:
        bullets.append("- Numerical claims dominate the paper.")
    if t.ablation_studies_expected:
        bullets.append("- Ablation studies are expected.")
    if t.multi_seed_required:
        bullets.append("- Multi-seed runs (typically ≥3) are required for quantitative claims.")
    out.extend(bullets)
    out.append("")
    return out


def _section_forbidden(v: Venue) -> list[str]:
    out = ["## 4. Forbidden constructions", ""]
    if not v.forbidden_constructions:
        out.append("(none declared)")
        out.append("")
        return out
    out.append("| Severity | Pattern | Reason |")
    out.append("|---|---|---|")
    for fc in v.forbidden_constructions:
        pattern = fc.pattern.replace("|", r"\|")
        reason = fc.reason.replace("|", r"\|")
        out.append(f"| {fc.severity} | `{pattern}` | {reason} |")
    out.append("")
    return out


def _section_citation(v: Venue) -> list[str]:
    f = v.format
    out = ["## 5. Citation style", ""]
    out.append(f"- Citation style: **{f.citation_style or '(unspecified)'}**.")
    out.append(f"- Bibliography style: **{f.bibliography_style or '(unspecified)'}**.")
    out.append("")
    return out


def _section_required(v: Venue) -> list[str]:
    s = v.structure
    out = ["## 6. Required sections + abstract length", ""]
    if s.required_sections:
        for sec in s.required_sections:
            out.append(f"  - **{sec}**")
        out.append("")
    if s.abstract_word_target is not None:
        rng = ""
        if s.abstract_word_min and s.abstract_word_max:
            rng = f" (typical range: {s.abstract_word_min} to {s.abstract_word_max} words)"
        out.append(f"Abstract: target **{s.abstract_word_target} words**{rng}.")
        out.append("")
    return out


def _section_corpus(v: Venue) -> list[str]:
    sc = v.sample_corpus
    out = ["## 7. Sample corpus pointers", ""]
    if sc is None:
        out.append("(no sample corpus configured)")
        out.append("")
        return out
    out.append(f"- Query method: `{sc.query_method}`.")
    if sc.filter_template:
        out.append(f"- Filter template: `{sc.filter_template}`.")
    if sc.recommended_year_range:
        out.append(
            f"- Recommended year range: {sc.recommended_year_range[0]} to "
            f"{sc.recommended_year_range[-1]}."
        )
    if sc.diversity_topics:
        out.append("- Diversity topics:")
        for t in sc.diversity_topics:
            out.append(f"  - {t}")
    if sc.rka_tag:
        out.append(f"- RKA tag for ingested samples: `{sc.rka_tag}`.")
    out.append("")
    return out


def _section_review_dimensions(v: Venue) -> list[str]:
    if not v.review_dimensions:
        return []
    out = ["## 8. Review dimensions (what reviewers score)", ""]
    out.append("| Dimension | Weight |")
    out.append("|---|---|")
    for rd in v.review_dimensions:
        out.append(f"| {rd.name} | {rd.weight} |")
    out.append("")
    return out


def _section_template_notes(v: Venue) -> list[str]:
    f = v.format
    out = ["## Template notes", ""]
    if f.template_id:
        out.append(f"- Template registry key: `{f.template_id}` "
                   f"(see `references/template_registry.md`).")
    out.append(f"- Default engine: `{f.engine_default}`.")
    if f.engines_supported and set(f.engines_supported) != {f.engine_default}:
        out.append(
            f"- Other supported engines: {', '.join(e for e in f.engines_supported if e != f.engine_default)}."
        )
    out.append("")
    return out


def _section_references_block(v: Venue) -> list[str]:
    out = ["## References (CFP + author guides)", ""]
    if v.cfp.primary_url:
        out.append(f"- Primary CFP: {v.cfp.primary_url}")
    if v.cfp.author_guide_url:
        out.append(f"- Author guide: {v.cfp.author_guide_url}")
    if v.cfp.checklist_url:
        out.append(f"- Checklist / extras: {v.cfp.checklist_url}")
    if v.cfp.last_verified:
        out.append(f"- Last verified: {v.cfp.last_verified}")
    if v.inherits_from:
        out.append(f"- Inherits from base spec: `{v.inherits_from}`")
    out.append("")
    return out


# ---------------------------------------------------------------------------
# Top-level render
# ---------------------------------------------------------------------------


def render_md(v: Venue) -> str:
    """Render the AUTO-GENERATED region only (without markers)."""
    blocks = (
        _header(v)
        + _section_sections_and_order(v)
        + _section_page_limit(v)
        + _section_tone(v)
        + _section_forbidden(v)
        + _section_citation(v)
        + _section_required(v)
        + _section_corpus(v)
        + _section_review_dimensions(v)
        + _section_template_notes(v)
        + _section_references_block(v)
    )
    return "\n".join(blocks).rstrip() + "\n"


def write_md(v: Venue) -> Path:
    """Write <id>.md. Preserves any non-auto-generated prelude/tail.
    Returns the path written."""
    path = _md_path(v.id)
    auto_body = render_md(v).rstrip()

    notes_path = _notes_path(v.id)
    notes_text = ""
    if notes_path:
        notes_text = "\n\n" + notes_path.read_text(encoding="utf-8").rstrip() + "\n"

    new_block = f"{BEGIN_MARKER}\n\n{auto_body}\n\n{END_MARKER}"

    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if BEGIN_MARKER in existing and END_MARKER in existing:
            before, _, rest = existing.partition(BEGIN_MARKER)
            _, _, after = rest.partition(END_MARKER)
            updated = f"{before}{new_block}{after}".rstrip() + "\n"
        else:
            # Existing MD predates auto-gen; replace entirely (preserve
            # nothing — the Phase W1 migration overwrites the Phase 2
            # hand-written MDs).
            updated = new_block + notes_text + "\n" if not notes_text else new_block + notes_text
            if not updated.endswith("\n"):
                updated += "\n"
    else:
        updated = new_block + notes_text + ("\n" if not notes_text else "")
        if not updated.endswith("\n"):
            updated += "\n"

    path.write_text(updated, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("venue_id", nargs="?", default=None,
                        help="venue id to render (omit with --all)")
    parser.add_argument("--all", action="store_true",
                        help="regenerate .md for every venue")
    parser.add_argument("--stdout", action="store_true",
                        help="print the rendered MD to stdout instead of writing")
    args = parser.parse_args(argv)

    if args.all and args.venue_id:
        print("error: --all and venue_id are mutually exclusive", file=sys.stderr)
        return 2

    if args.all:
        venues = load_all_venues()
        for vid, v in sorted(venues.items()):
            if args.stdout:
                print(f"--- {vid} ---")
                print(render_md(v))
            else:
                p = write_md(v)
                print(f"wrote {p.relative_to(SKILL_ROOT)}")
        return 0

    if not args.venue_id:
        print("error: provide venue_id or --all", file=sys.stderr)
        return 2

    v = load_venue(args.venue_id)
    if args.stdout:
        sys.stdout.write(render_md(v))
        return 0
    p = write_md(v)
    print(f"wrote {p.relative_to(SKILL_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
