// Inline-style centralization. D5/D6 polish may extract to a CSS module;
// for D3/D4 scaffolding, inline keeps the dependency surface minimal.
import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  shell: {
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Inter', sans-serif",
    maxWidth: 880,
    margin: "0 auto",
    padding: "32px 24px",
    color: "#1a1a1a",
  },
  header: { marginBottom: 24 },
  title: { fontSize: 24, fontWeight: 600, margin: 0 },
  tagline: { marginTop: 6, fontSize: 14, color: "#4a4a4a", lineHeight: 1.5 },
  nav: { display: "flex", gap: 4, marginTop: 16 },
  navBtn: {
    background: "transparent",
    border: "1px solid #e3e3e3",
    borderRadius: 6,
    padding: "6px 12px",
    fontSize: 13,
    cursor: "pointer",
  },
  navActive: {
    background: "#1a1a1a",
    color: "#fff",
    border: "1px solid #1a1a1a",
    borderRadius: 6,
    padding: "6px 12px",
    fontSize: 13,
    cursor: "pointer",
  },
  panel: {
    border: "1px solid #e3e3e3",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    background: "#fafafa",
  },
  panelTitle: { fontSize: 16, fontWeight: 600, margin: "0 0 12px 0" },
  panelSubtitle: { fontSize: 13, fontWeight: 500, margin: "16px 0 8px 0", color: "#4a4a4a" },
  dl: {
    display: "grid",
    gridTemplateColumns: "180px 1fr",
    rowGap: 6,
    columnGap: 12,
    margin: 0,
    fontSize: 13,
  },
  muted: { fontSize: 12, color: "#6a6a6a" },
  grid: { display: "flex", flexDirection: "column", gap: 8, marginTop: 12 },
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: 10,
    border: "1px solid #ececec",
    borderRadius: 6,
    background: "#fff",
    cursor: "pointer",
  },
  rowBody: { display: "flex", flexDirection: "column", gap: 4, flex: 1 },
  rowName: {
    fontSize: 14,
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  formatTag: {
    fontSize: 10,
    background: "#f0f0f0",
    padding: "1px 6px",
    borderRadius: 3,
    color: "#6a6a6a",
    textTransform: "uppercase",
  },
  detected: { fontSize: 11, color: "#137333", marginLeft: 4 },
  rowPath: {
    fontSize: 11,
    color: "#6a6a6a",
    fontFamily: "ui-monospace, monospace",
  },
  verifyRow: {
    display: "flex",
    gap: 6,
    marginTop: 4,
    flexWrap: "wrap",
    alignItems: "center",
  },
  pill: {
    fontSize: 10,
    padding: "2px 6px",
    borderRadius: 10,
    fontWeight: 500,
  },
  toggleAll: {
    background: "transparent",
    border: "none",
    color: "#1a73e8",
    padding: 0,
    marginTop: 12,
    cursor: "pointer",
    fontSize: 12,
  },
  actionBar: {
    marginTop: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  primaryBtn: {
    background: "#1a73e8",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 14,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  secondaryBtn: {
    background: "#fff",
    color: "#1a1a1a",
    border: "1px solid #e3e3e3",
    borderRadius: 6,
    padding: "6px 12px",
    fontSize: 12,
    cursor: "pointer",
  },
  outcomeBlock: {
    border: "1px solid #e3e3e3",
    borderRadius: 6,
    padding: 12,
    background: "#fff",
    fontSize: 12,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  outcomeRow: {},
  globalActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 12,
    marginBottom: 16,
  },
  perClientActions: {
    display: "flex",
    gap: 6,
    marginTop: 6,
    flexWrap: "wrap",
  },
  smallBtn: {
    background: "transparent",
    color: "#1a73e8",
    border: "none",
    fontSize: 11,
    padding: 0,
    cursor: "pointer",
    textDecoration: "underline",
  },
  ok: { color: "#137333" },
  bad: { color: "#a50e0e" },
};
