//! Stable launcher script for the bundled `rka-mcp` binary.
//!
//! Each supported MCP client (Claude Desktop, Claude Code, Cursor,
//! VSCode-Copilot, Codex CLI/App, Antigravity) references a single path
//! that never changes after first registration:
//!
//!   `~/Library/Application Support/RKA/bin/rka-mcp.sh`  (macOS)
//!
//! The script `exec`s the bundled binary from inside the current
//! `RKA.app` bundle. This indirection means the .app can be moved or
//! upgraded without re-writing every client's MCP config.
//!
//! Rewritten on every app launch so a moved .app still resolves.

use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use tauri::{AppHandle, Manager};

use crate::mcp_clients::stable_launcher_path;

pub fn write_stable_launcher(app: &AppHandle) -> Result<PathBuf> {
    let target = stable_launcher_path();
    let parent = target
        .parent()
        .ok_or_else(|| anyhow!("launcher path has no parent dir"))?;
    std::fs::create_dir_all(parent).context("create bin dir")?;

    let resource_dir = app
        .path()
        .resource_dir()
        .context("resource_dir unavailable")?;
    let bundled_binary = resource_dir.join("rka-mcp");

    let script = format!(
        "#!/usr/bin/env bash\n# Auto-generated by RKA.app — rewritten on each launch.\n# Do not edit.\nexec {:?} \"$@\"\n",
        bundled_binary
    );
    std::fs::write(&target, script).context("write launcher script")?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&target)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&target, perms)?;
    }

    if !bundled_binary.exists() {
        log::warn!(
            "Launcher written but bundled rka-mcp not found at {bundled_binary:?}; MCP clients will fail until the binary lands"
        );
        return Err(anyhow!("rka-mcp binary missing from resource dir"));
    }

    log::info!("Stable launcher written to {target:?}");
    Ok(target)
}
