"""Machine-readable ownership for the public RKA Core contracts.

This module deliberately separates *product ownership* from MCP
``operation_maturity``.  The latter is a usage-readiness hint and is not a
promise that an operation belongs to Core: frozen Writer compatibility,
shelved Agentic operations, and one legacy session operation all have their
own dispositions.

The E2.2 snapshots use these rules as the classification authority.  A new
REST operation defaults to Core; Writer paths, shelved Agentic paths, and
legacy paths must remain explicit.  MCP callers pass the Writer compatibility
set generated by ``operations_schema`` so that its category-based deprecation
authority is not duplicated here.
"""

from __future__ import annotations

from collections.abc import Collection
from typing import Literal


ContractDisposition = Literal[
    "core",
    "writer-compatibility",
    "agentic-unsupported",
    "core-legacy",
]

CORE: ContractDisposition = "core"
WRITER_COMPATIBILITY: ContractDisposition = "writer-compatibility"
AGENTIC_UNSUPPORTED: ContractDisposition = "agentic-unsupported"
CORE_LEGACY: ContractDisposition = "core-legacy"


# Frozen Writer REST adapters.  ``rka.api.app`` uses this same tuple for the
# runtime compatibility headers; snapshots additionally require every matching
# OpenAPI operation to be marked deprecated.
WRITER_REST_PATH_PREFIXES: tuple[str, ...] = (
    "/api/manuscripts",
    "/api/manuscript-source-proposals",
    "/api/planning",
    "/api/semantic-patches",
)


# Model-driven execution and Brain notification routes were assigned to the
# now-shelved Agentic product.  They remain callable for compatibility but are
# not part of rka-rest/v1.
AGENTIC_REST_OPERATIONS: frozenset[tuple[str, str]] = frozenset(
    {
        ("POST", "/api/summarize"),
        ("POST", "/api/enrich"),
        ("GET", "/api/notifications"),
        ("POST", "/api/notifications/clear"),
        ("GET", "/api/llm/status"),
        ("PUT", "/api/llm/config"),
        ("GET", "/api/llm/models"),
        ("POST", "/api/llm/check"),
        ("POST", "/api/summaries/generate"),
        ("POST", "/api/qa/ask"),
    }
)


# Historical summary/Q&A reads remain available only for old databases and
# clients.  New synthesis belongs outside Core.
CORE_LEGACY_REST_OPERATIONS: frozenset[tuple[str, str]] = frozenset(
    {
        ("GET", "/api/summaries"),
        ("GET", "/api/summaries/{summary_id}"),
        ("POST", "/api/summaries/{summary_id}/bless"),
        ("GET", "/api/qa/sessions"),
        ("GET", "/api/qa/sessions/{session_id}"),
        ("POST", "/api/qa/verify/{qa_log_id}/{source_index}"),
    }
)


AGENTIC_MCP_OPERATIONS: frozenset[str] = frozenset(
    {
        "summarize",
        "generate_summary",
        "brain_notifications",
        "brain_notifications_clear",
        "session_digest",
    }
)
CORE_LEGACY_MCP_OPERATIONS: frozenset[str] = frozenset({"reset_session"})


# The public transport is five tools by default.  Typed-operation ownership is
# classified separately because rka_query/rka_execute multiplex many branches.
MCP_TRANSPORT_TOOLS: tuple[str, ...] = (
    "rka_load_tools",
    "rka_help",
    "rka_query",
    "rka_describe",
    "rka_execute",
)


# REST does not currently expose per-route maturity metadata.  These rules are
# the REST equivalents of the Core-owned MCP preview families at the E2.2
# boundary: experiments, hooks, interpretation staging, and claim-scope
# versioning.  They are intentionally *not* ownership rules.
PREVIEW_REST_TAGS: frozenset[str] = frozenset({"experiments", "hooks", "interpretation-staging"})
PREVIEW_REST_OPERATIONS: frozenset[tuple[str, str]] = frozenset(
    {
        ("GET", "/api/claims/{claim_id}/scope"),
        ("POST", "/api/claims/{claim_id}/scope"),
    }
)


def is_writer_compatibility_path(path: str) -> bool:
    """Return whether ``path`` belongs to frozen Writer REST compatibility."""

    return any(
        path == prefix or path.startswith(f"{prefix}/") for prefix in WRITER_REST_PATH_PREFIXES
    )


def rest_operation_disposition(
    method: str,
    path: str,
    *,
    deprecated: bool,
) -> ContractDisposition:
    """Classify one OpenAPI operation into exactly one product disposition.

    Writer compatibility has two independent public signals: a known Writer
    path and ``deprecated: true`` in OpenAPI.  Requiring both prevents a route
    from silently entering or leaving the supported Core snapshot.
    """

    key = (method.upper(), path)
    writer_path = is_writer_compatibility_path(path)
    if writer_path:
        if not deprecated:
            raise ValueError(f"Writer compatibility operation {key!r} is not deprecated in OpenAPI")
        return WRITER_COMPATIBILITY
    if deprecated:
        raise ValueError(
            f"Deprecated REST operation {key!r} has no explicit compatibility disposition"
        )
    if key in AGENTIC_REST_OPERATIONS:
        return AGENTIC_UNSUPPORTED
    if key in CORE_LEGACY_REST_OPERATIONS:
        return CORE_LEGACY
    return CORE


def mcp_operation_disposition(
    operation: str,
    *,
    writer_operations: Collection[str],
) -> ContractDisposition:
    """Classify one typed MCP operation independently of usage maturity."""

    memberships = [
        WRITER_COMPATIBILITY if operation in writer_operations else None,
        AGENTIC_UNSUPPORTED if operation in AGENTIC_MCP_OPERATIONS else None,
        CORE_LEGACY if operation in CORE_LEGACY_MCP_OPERATIONS else None,
    ]
    matches = [value for value in memberships if value is not None]
    if len(matches) > 1:
        raise ValueError(f"MCP operation {operation!r} has conflicting dispositions: {matches}")
    return matches[0] if matches else CORE


def rest_operation_maturity(
    method: str,
    path: str,
    *,
    tags: Collection[str],
) -> Literal["stable", "preview"]:
    """Return the E2.2 REST usage-readiness signal for a Core operation."""

    if (method.upper(), path) in PREVIEW_REST_OPERATIONS:
        return "preview"
    if PREVIEW_REST_TAGS.intersection(tags):
        return "preview"
    return "stable"


__all__ = [
    "AGENTIC_MCP_OPERATIONS",
    "AGENTIC_REST_OPERATIONS",
    "AGENTIC_UNSUPPORTED",
    "CORE",
    "CORE_LEGACY",
    "CORE_LEGACY_MCP_OPERATIONS",
    "CORE_LEGACY_REST_OPERATIONS",
    "ContractDisposition",
    "MCP_TRANSPORT_TOOLS",
    "PREVIEW_REST_OPERATIONS",
    "PREVIEW_REST_TAGS",
    "WRITER_COMPATIBILITY",
    "WRITER_REST_PATH_PREFIXES",
    "is_writer_compatibility_path",
    "mcp_operation_disposition",
    "rest_operation_disposition",
    "rest_operation_maturity",
]
